import ExpandableText from "../components/ExpandableText";

const PlaygroundPage = () => {
  return (
    <ExpandableText
      text="  Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa corporis explicabo ea consectetur quas. Provident rem tenetur obcaecati? Soluta, nihil hic mollitia iure id laborum aliquam quo quod asperiores inventore, magnam voluptatum. Sed eaque enim excepturi at, necessitatibus incidunt quasi tempore quam dignissimos error ad eveniet dolor velit quaerat. Ipsa fugit aut, impedit eligendi deserunt quia omnis veniam deleniti incidunt cumque repellat in, autem quam atque praesentium excepturi voluptatum numquam totam, cupiditate culpa quos facilis. A reiciendis voluptates voluptatibus modi aliquam molestiae itaque delectus, vitae quasi debitis, esse commodi reprehenderit minus rerum dolore amet voluptatum accusamus voluptas, at sint sit?     Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi nihil unde tempora nemo est, nisi corrupti magni ullam amet ex incidunt accusamus odit. Modi illum cum ad suscipit sequi consectetur laudantium quaerat culpa placeat corrupti. Tempore nemo, animi exercitationem inventore eum nisi ipsam odit consequatur et quibusdam culpa quam magnam voluptatum officiis, vitae deleniti praesentium ipsum repudiandae ea dolorem excepturi! Officia asperiores, natus in tempore nemo libero accusantium saepe! Cumque velit recusandae assumenda ut quaerat unde autem quas laboriosam consequatur provident eum tempore eligendi temporibus eius, quia illo officiis blanditiis possimus, ullam asperiores culpa corrupti. Sed corporis, voluptatum eius minus perferendis error maiores quia, assumenda dicta quibusdam ipsam nesciunt ipsum dolores optio voluptatibus alias numquam quis aliquid ut, dignissimos reprehenderit non adipisci? Eveniet debitis cumque obcaecati totam animi veritatis expedita ducimus nemo minus laborum laudantium, maiores doloremque quae quis quas quibusdam possimus velit consectetur tempore, necessitatibus ex vel ipsum. Possimus consectetur quis aliquid officia laboriosam atque! Maxime, suscipit impedit? Ullam est quam quis exercitationem corrupti unde quidem laudantium nostrum optio ad minima repudiandae inventore rem quod mollitia sit soluta deserunt, libero eligendi blanditiis. Nesciunt consequuntur doloribus quibusdam, molestiae perspiciatis inventore quis autem porro soluta unde possimus eum praesentium dolorum dignissimos.
"
    />
  );
};

export default PlaygroundPage;
